### ISSUE TITLE
arch-fs

### ISSUE THREAD

**Issue by bagas8888** [wahasa/Arch#1]
proot warning: can't sanitize binding "arch-fs/root": No such file or directory
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/arch-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.

**Comment by andynolife** [comment]
same issue

**Comment by wahasa** [comment]
Thank you for telling me,?
I more or less know the cause, as in this picture there is a difference in the file code even though the name was changed when downloading it in wget.

For comparison, there are 4 files in this image, I hope you understand and I will change it a bit for the Arch Linux script now.

![Screenshot_20241224_180045_Termux](https://github.com/user-attachments/assets/093637c1-143d-45b1-aa31-c148ebeda99b)
